# Generated by Django 2.2 on 2021-06-11 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='Pata nahi kya cheez hai'),
            preserve_default=False,
        ),
    ]
